import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { signInWithGoogle, auth } from "../../lib/firebase";
import {
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  sendPasswordResetEmail
} from "firebase/auth";
import { X, Shield, FileText, ChevronRight } from "lucide-react";

// ── Terms & Conditions Content ───────────────────────────────────────────────
function TermsModal({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 bg-black/90 backdrop-blur-md z-[200] flex items-center justify-center p-4">
      <motion.div
        initial={{ scale: 0.95, opacity: 0, y: 10 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.95, opacity: 0, y: 10 }}
        className="bg-[#0F1115] border border-white/10 w-full max-w-2xl max-h-[85vh] flex flex-col relative shadow-[0_20px_60px_rgba(0,0,0,0.8)]"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-white/5 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
              <FileText size={14} className="text-emerald-500" />
            </div>
            <div>
              <div className="text-[8px] font-mono text-emerald-500 uppercase tracking-widest">
                // LEGAL_DOCUMENT
              </div>
              <h3 className="text-sm font-bold text-white uppercase tracking-tight font-mono">
                Terms & Conditions
              </h3>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-500 hover:text-white border border-white/5 hover:border-white/20 transition-colors"
          >
            <X size={14} />
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="overflow-y-auto flex-1 p-6 space-y-6 text-[11px] font-mono text-slate-400 leading-relaxed">

          <div className="text-[9px] text-slate-600 uppercase tracking-widest">
            Last updated: June 2026 · Version 1.0 · Beta
          </div>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-white uppercase tracking-widest text-emerald-500">
              1. Acceptance of Terms
            </h4>
            <p>
              By creating an account and using ArshMind ("the Service", "the Platform"), you agree to be bound by
              these Terms and Conditions. If you do not agree to these terms, you may not access or use the Service.
              These terms apply to all users, visitors, and others who access or use the Service.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              2. Nature of the Service
            </h4>
            <p>
              ArshMind is a <span className="text-white">financial and career simulation tool</span> powered by
              artificial intelligence. The scenarios, projections, timelines, and recommendations generated by the
              platform are <span className="text-amber-400">for informational and educational purposes only</span>.
            </p>
            <p>
              ArshMind does <span className="text-rose-400 font-bold">NOT</span> provide:
            </p>
            <ul className="space-y-1 pl-4">
              {[
                "Registered financial advice or investment advisory services",
                "Legal, tax, or accounting counsel",
                "Guaranteed financial outcomes or returns",
                "SEBI-registered portfolio management services",
              ].map(item => (
                <li key={item} className="flex gap-2">
                  <span className="text-rose-500 shrink-0">×</span>
                  {item}
                </li>
              ))}
            </ul>
            <p>
              Always consult a qualified financial advisor, CA, or legal professional before making major
              financial or career decisions.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              3. Data Collection & Privacy
            </h4>
            <p>
              By using ArshMind, you consent to the collection and processing of the personal and financial
              information you provide during onboarding ("Profile Data"). This includes but is not limited to:
              your name, age, location, income, savings, assets, liabilities, and career goals.
            </p>
            <p>
              Your Profile Data is:
            </p>
            <ul className="space-y-1 pl-4">
              {[
                "Stored securely in Google Firebase Firestore with role-level security rules",
                "Used solely to generate personalized AI-driven financial scenarios",
                "Never sold to third parties or used for advertising purposes",
                "Accessible only by you through your authenticated account",
              ].map(item => (
                <li key={item} className="flex gap-2">
                  <span className="text-emerald-500 shrink-0">✓</span>
                  {item}
                </li>
              ))}
            </ul>
            <p>
              AI scenario generation sends anonymized profile parameters to Google Gemini API.
              No personally identifiable information (PII) such as your name or email is transmitted to the AI model.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              4. Beta Service Disclaimer
            </h4>
            <p>
              ArshMind is currently in <span className="text-amber-400 font-bold">Beta</span>. The Service is
              provided "as is" and "as available" without warranties of any kind, either express or implied.
              We do not guarantee that the Service will be uninterrupted, error-free, or that defects will be corrected.
            </p>
            <p>
              Features, pricing, and availability may change at any time during the Beta period without prior notice.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              5. User Responsibilities
            </h4>
            <p>You agree to:</p>
            <ul className="space-y-1 pl-4">
              {[
                "Provide accurate and truthful information during onboarding",
                "Maintain the confidentiality of your account credentials",
                "Not attempt to reverse-engineer, scrape, or misuse the platform",
                "Not use the Service for any unlawful purpose",
                "Take sole responsibility for any decisions made based on AI-generated output",
              ].map(item => (
                <li key={item} className="flex gap-2">
                  <span className="text-slate-500 shrink-0">//</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              6. Limitation of Liability
            </h4>
            <p>
              To the fullest extent permitted by applicable law, ArshMind and its creators shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages — including but not limited
              to loss of profits, data, or goodwill — arising out of or in connection with your use of the Service
              or reliance on any AI-generated content.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              7. Intellectual Property
            </h4>
            <p>
              All content, design, code, and AI models underlying ArshMind are the intellectual property of the
              ArshMind development team. You may not copy, reproduce, distribute, or create derivative works
              without explicit written permission.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              8. Account Termination
            </h4>
            <p>
              We reserve the right to suspend or terminate your account at our sole discretion if you violate
              these Terms. You may delete your account at any time by contacting us — all associated data will
              be permanently removed within 30 days.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              9. Governing Law
            </h4>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of India.
              Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of
              the courts located in India.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              10. Changes to Terms
            </h4>
            <p>
              We reserve the right to update these Terms at any time. Continued use of the Service after
              changes constitutes acceptance of the revised Terms. We will notify users of material changes
              via in-app notification or email.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
              11. Contact
            </h4>
            <p>
              For questions about these Terms, privacy concerns, or data deletion requests, contact us at:
              <a className="text-white ml-2 underline" href="mailto:testingnewold@gmail.com">
                testingnewold@gmail.com
              </a>
            </p>
          </section>

          <div className="pt-4 border-t border-white/5 text-[9px] text-slate-600 uppercase tracking-widest text-center">
            // END_OF_LEGAL_DOCUMENT · ARSHMIND_BETA_v1.0
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-white/5 shrink-0">
          <button
            onClick={onClose}
            className="w-full py-3 bg-emerald-500 hover:bg-emerald-600 text-black font-mono font-bold text-[10px] uppercase tracking-widest transition-all"
          >
            [ UNDERSTOOD — CLOSE DOCUMENT ]
          </button>
        </div>
      </motion.div>
    </div>
  );
}

// ── Main BootScreen ──────────────────────────────────────────────────────────
export default function BootScreen({ onComplete }: { onComplete: () => void }) {
  const [progress, setProgress] = useState(0);
  const [logs, setLogs] = useState<string[]>([]);
  const [isSigningIn, setIsSigningIn] = useState(false);

  // Auth States
  const [authMode, setAuthMode] = useState<"CHOICE" | "SIGNIN" | "SIGNUP" | "RESET">("CHOICE");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [authError, setAuthError] = useState("");
  const [authSuccessMsg, setAuthSuccessMsg] = useState("");

  // T&C State
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [showTermsModal, setShowTermsModal] = useState(false);
  const [termsError, setTermsError] = useState(false);

  const allLogs = [
    "// SYSTEM INITIALIZING...",
    "// LOADING AI PLANNING ENGINE...",
    "// CALIBRATING LIFE VECTORS...",
    "// ANALYZING TEMPORAL BRANCHES...",
    "// COGNITIVE LOGIC ONLINE.",
    "// READY TO COMMENCE OPERATIVE SELECTION."
  ];

  useEffect(() => {
    let logIndex = 0;
    const interval = setInterval(() => {
      if (logIndex < allLogs.length) {
        setLogs(prev => [...prev, allLogs[logIndex]]);
        logIndex++;
      } else {
        clearInterval(interval);
      }
    }, 400);

    const progressInterval = setInterval(() => {
      setProgress(prev => {
        if (prev >= 100) { clearInterval(progressInterval); return 100; }
        return prev + 1;
      });
    }, 15);

    return () => { clearInterval(interval); clearInterval(progressInterval); };
  }, []);

  const clearModes = (mode: typeof authMode) => {
    setAuthMode(mode);
    setAuthError("");
    setAuthSuccessMsg("");
    setPassword("");
    setConfirmPassword("");
    setTermsAccepted(false);
    setTermsError(false);
  };

  const handleGoogleSignIn = async () => {
    setIsSigningIn(true);
    setAuthError("");
    setAuthSuccessMsg("");
    try {
      await signInWithGoogle();
      onComplete();
    } catch (error: any) {
      setAuthError(`// GOOGLE_SSO_FAILED: ${error.message || "Unknown error"}`);
    } finally {
      setIsSigningIn(false);
    }
  };

  const handleEmailSignIn = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !password) {
      setAuthError("// AUTH_ERROR: Please enter both email and password.");
      return;
    }
    setIsSigningIn(true);
    setAuthError("");
    setAuthSuccessMsg("");
    try {
      await signInWithEmailAndPassword(auth, email, password);
      onComplete();
    } catch (error: any) {
      let errMsg = error.message;
      if (
        error.code === "auth/invalid-credential" ||
        error.code === "auth/wrong-password" ||
        error.code === "auth/user-not-found"
      ) {
        errMsg = "Invalid authentication parameters (incorrect credentials).";
      } else if (error.code === "auth/invalid-email") {
        errMsg = "Malformed email address structure.";
      }
      setAuthError(`// AUTH_FAILED (${error.code || "unknown"}): ${errMsg}`);
    } finally {
      setIsSigningIn(false);
    }
  };

  const handleEmailSignUp = async (e: React.FormEvent) => {
    e.preventDefault();

    // T&C gate — must be checked before anything else
    if (!termsAccepted) {
      setTermsError(true);
      setAuthError("// COMPLIANCE_ERROR: You must accept the Terms & Conditions to create an account.");
      return;
    }

    if (!email || !password || !confirmPassword) {
      setAuthError("// CAPTURE_ERROR: Complete all security coordinates.");
      return;
    }
    if (password !== confirmPassword) {
      setAuthError("// CAPTURE_ERROR: Cryptographic security keys do not match.");
      return;
    }
    if (password.length < 6) {
      setAuthError("// CAPTURE_ERROR: Password is too weak (min 6 characters required).");
      return;
    }

    setIsSigningIn(true);
    setAuthError("");
    setAuthSuccessMsg("");
    try {
      await createUserWithEmailAndPassword(auth, email, password);
      onComplete();
    } catch (error: any) {
      let errMsg = error.message;
      if (error.code === "auth/email-already-in-use") {
        errMsg =
          "This email coordinate is already registered. If you previously signed up via Google SSO, use the Google sign-in option or reset your password.";
      } else if (error.code === "auth/weak-password") {
        errMsg = "Security key is too fragile (weak password).";
      }
      setAuthError(`// REGISTRATION_FAILED: ${errMsg}`);
    } finally {
      setIsSigningIn(false);
    }
  };

  const handlePasswordReset = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) {
      setAuthError("// TRANS_ERROR: Please specify a valid destination email.");
      return;
    }
    setIsSigningIn(true);
    setAuthError("");
    setAuthSuccessMsg("");
    try {
      await sendPasswordResetEmail(auth, email);
      setAuthSuccessMsg(
        "// TRANSMISSION_CONFIRMED: Password reset vector sent to target inbox. Inspect coordinates shortly."
      );
    } catch (error: any) {
      setAuthError(`// RESET_FAILED: ${error.message}`);
    } finally {
      setIsSigningIn(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black flex flex-col items-center justify-center z-50 p-6 overflow-hidden select-none">

      {/* T&C Modal */}
      <AnimatePresence>
        {showTermsModal && (
          <TermsModal onClose={() => setShowTermsModal(false)} />
        )}
      </AnimatePresence>

      {/* Boot Rings */}
      <div className="relative mb-6 w-36 h-36 flex items-center justify-center shrink-0">
        <div className="absolute w-32 h-32 rounded-full border border-emerald-500/10 animate-[spin_10s_linear_infinite]" />
        <div className="absolute w-26 h-26 rounded-full border border-dashed border-emerald-500/20 animate-[spin_15s_linear_infinite_reverse]" />
        <motion.div
          animate={{ scale: [0.95, 1.05, 0.95], opacity: [0.4, 0.8, 0.4] }}
          transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
          className="absolute w-24 h-24 rounded-full border border-emerald-500/30 flex items-center justify-center shadow-[0_0_25px_rgba(16,185,129,0.08)]"
        />
        <motion.div
          animate={{ scale: [0.9, 1.1, 0.9], opacity: [0.6, 0.9, 0.6] }}
          transition={{ duration: 2.2, repeat: Infinity, ease: "easeInOut", delay: 0.3 }}
          className="absolute w-18 h-18 rounded-full border border-dashed border-emerald-500/40"
        />
        <div className="text-emerald-500 text-lg font-mono relative z-10 drop-shadow-[0_0_8px_rgba(16,185,129,0.8)]">
          ◆
        </div>
      </div>

      {/* Logo */}
      <div className="text-center mb-4 shrink-0">
        <h1 className="text-2xl font-mono tracking-[0.4em] text-white uppercase font-bold">
          ARSH<span className="text-emerald-500">MIND</span>
        </h1>
        <p className="text-slate-600 font-mono text-[8px] uppercase tracking-widest mt-1">
          // FUTURE_OS_DEPLOYMENT_V2
        </p>
      </div>

      <AnimatePresence mode="wait">
        {/* Boot Terminal */}
        {progress < 100 ? (
          <motion.div
            key="terminal"
            initial={{ opacity: 1 }}
            exit={{ opacity: 0, y: -10 }}
            className="w-full max-w-sm flex flex-col items-center"
          >
            <div className="w-full bg-[#070708] border border-white/5 p-4 rounded-none mb-6 font-mono text-[10px] space-y-1.5 h-28 overflow-y-auto no-scrollbar">
              {logs.map((log, i) => {
                const isActive = i === logs.length - 1 && progress < 100;
                return (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`leading-relaxed tracking-wider ${isActive ? "text-emerald-400 animate-pulse font-bold" : "text-slate-500"}`}
                  >
                    {log}
                  </motion.div>
                );
              })}
            </div>
            <div className="w-full bg-white/5 h-[3px] mb-6 overflow-hidden relative">
              <div
                className="h-full bg-emerald-500 transition-all duration-100 shadow-[0_0_10px_rgba(16,185,129,0.5)]"
                style={{ width: `${progress}%` }}
              />
            </div>
          </motion.div>
        ) : (
          /* Auth Screen */
          <motion.div
            key="auth"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="w-full max-w-md flex flex-col items-center"
          >
            {/* Error/Success banner */}
            {(authError || authSuccessMsg) && (
              <div className="w-full bg-[#0E0608] border border-red-500/20 text-[9px] p-3 mb-4 font-mono uppercase tracking-wider space-y-1 select-text">
                {authError && <div className="text-rose-500">{authError}</div>}
                {authSuccessMsg && <div className="text-emerald-400">{authSuccessMsg}</div>}
              </div>
            )}

            {/* CHOICE */}
            {authMode === "CHOICE" && (
              <div className="w-full space-y-3">
                <div className="text-[9px] font-mono text-slate-500 text-center uppercase tracking-widest mb-2">
                  // DEPLOY_AUTH_PROVIDER_PARAMETERS
                </div>
                <button
                  onClick={handleGoogleSignIn}
                  disabled={isSigningIn}
                  className="w-full py-3.5 border border-emerald-500/30 hover:border-emerald-500 bg-emerald-500/5 hover:bg-emerald-500/10 text-emerald-400 font-mono text-[10px] uppercase tracking-[0.2em] transition-all flex items-center justify-center gap-2"
                >
                  {isSigningIn ? "[ AUTHORIZING... ]" : "[ SIGN IN WITH GOOGLE ]"}
                </button>
                <div className="flex gap-3">
                  <button
                    onClick={() => clearModes("SIGNIN")}
                    disabled={isSigningIn}
                    className="flex-1 py-3 border border-white/10 hover:border-emerald-500/40 bg-white/5 hover:bg-emerald-500/5 text-slate-400 hover:text-emerald-400 font-mono text-[9px] uppercase tracking-[0.15em] transition-all"
                  >
                    // EMAIL_SIGN_IN
                  </button>
                  <button
                    onClick={() => clearModes("SIGNUP")}
                    disabled={isSigningIn}
                    className="flex-1 py-3 border border-white/10 hover:border-emerald-500/40 bg-white/5 hover:bg-emerald-500/5 text-slate-400 hover:text-emerald-400 font-mono text-[9px] uppercase tracking-[0.15em] transition-all"
                  >
                    // REGISTER_OPERATIVE
                  </button>
                </div>
                {auth.currentUser && (
                  <div className="pt-3 text-center">
                    <button
                      onClick={onComplete}
                      className="text-emerald-400 font-mono text-[9px] hover:underline uppercase tracking-wider"
                    >
                      [ BYPASS AS AUTHENTICATED: {auth.currentUser.email} &gt;&gt; ]
                    </button>
                  </div>
                )}
              </div>
            )}

            {/* SIGN IN */}
            {authMode === "SIGNIN" && (
              <form onSubmit={handleEmailSignIn} className="w-full space-y-4">
                <div className="text-[9px] font-mono text-slate-500 text-center uppercase tracking-widest mb-1">
                  // ACCESS COORDINATES FORM
                </div>
                <div className="space-y-3">
                  <div>
                    <label className="block text-[8px] font-mono text-slate-500 uppercase tracking-widest mb-1.5">
                      // EMAIL_ENDPOINT
                    </label>
                    <input
                      type="email"
                      value={email}
                      required
                      placeholder="ENTER_EMAIL_COORDINATES"
                      onChange={e => setEmail(e.target.value)}
                      className="w-full bg-[#070708] border border-white/10 hover:border-white/20 focus:border-emerald-500/50 p-3 text-[10px] font-mono text-white placeholder:text-slate-600 focus:outline-none transition-all"
                    />
                  </div>
                  <div>
                    <label className="block text-[8px] font-mono text-slate-500 uppercase tracking-widest mb-1.5">
                      // ACCESS_SECURITY_KEY
                    </label>
                    <input
                      type="password"
                      value={password}
                      required
                      placeholder="ENTER_PASSWORD_COORDINATES"
                      onChange={e => setPassword(e.target.value)}
                      className="w-full bg-[#070708] border border-white/10 hover:border-white/20 focus:border-emerald-500/50 p-3 text-[10px] font-mono text-white placeholder:text-slate-600 focus:outline-none transition-all"
                    />
                  </div>
                </div>
                <button
                  type="submit"
                  disabled={isSigningIn}
                  className="w-full py-3.5 bg-emerald-500 hover:bg-emerald-600 text-black font-mono font-bold text-[10px] uppercase tracking-[0.2em] transition-all"
                >
                  {isSigningIn ? "[ EXECUTING AUTHENTICATION... ]" : "[ AUTHORIZE INTEGRATION ]"}
                </button>
                <div className="flex justify-between items-center text-[9px] font-mono uppercase tracking-widest pt-2">
                  <button type="button" onClick={() => clearModes("CHOICE")} className="text-slate-500 hover:text-emerald-500 transition-colors">
                    &lt; RETURN_BACK
                  </button>
                  <button type="button" onClick={() => clearModes("RESET")} className="text-slate-500 hover:text-rose-500 transition-colors">
                    // FORGOT_SECURITY_KEY
                  </button>
                </div>
              </form>
            )}

            {/* SIGN UP */}
            {authMode === "SIGNUP" && (
              <form onSubmit={handleEmailSignUp} className="w-full space-y-4">
                <div className="text-[9px] font-mono text-slate-500 text-center uppercase tracking-widest mb-1">
                  // REGISTER_NEW_OPERATIVE
                </div>
                <div className="space-y-3">
                  <div>
                    <label className="block text-[8px] font-mono text-slate-500 uppercase tracking-widest mb-1.5">
                      // EMAIL_ENDPOINT
                    </label>
                    <input
                      type="email"
                      value={email}
                      required
                      placeholder="ENTER_EMAIL_COORDINATES"
                      onChange={e => setEmail(e.target.value)}
                      className="w-full bg-[#070708] border border-white/10 hover:border-white/20 focus:border-emerald-500/50 p-3 text-[10px] font-mono text-white placeholder:text-slate-600 focus:outline-none transition-all"
                    />
                  </div>
                  <div>
                    <label className="block text-[8px] font-mono text-slate-500 uppercase tracking-widest mb-1.5">
                      // ACCESS_SECURITY_KEY
                    </label>
                    <input
                      type="password"
                      value={password}
                      required
                      placeholder="CREATE_PASSWORD_KEYS"
                      onChange={e => setPassword(e.target.value)}
                      className="w-full bg-[#070708] border border-white/10 hover:border-white/20 focus:border-emerald-500/50 p-3 text-[10px] font-mono text-white placeholder:text-slate-600 focus:outline-none transition-all"
                    />
                  </div>
                  <div>
                    <label className="block text-[8px] font-mono text-slate-500 uppercase tracking-widest mb-1.5">
                      // RE_ENTER_SECURITY_KEY
                    </label>
                    <input
                      type="password"
                      value={confirmPassword}
                      required
                      placeholder="RECONFIRM_PASSWORD_KEYS"
                      onChange={e => setConfirmPassword(e.target.value)}
                      className="w-full bg-[#070708] border border-white/10 hover:border-white/20 focus:border-emerald-500/50 p-3 text-[10px] font-mono text-white placeholder:text-slate-600 focus:outline-none transition-all"
                    />
                  </div>
                </div>

                {/* ── Terms & Conditions Checkbox ── */}
                <div className={`p-4 border transition-all duration-300 ${termsError && !termsAccepted ? "border-rose-500/40 bg-rose-500/5" : "border-white/10 bg-white/[0.02]"}`}>
                  <label className="flex items-start gap-3 cursor-pointer group select-none">
                    {/* Custom checkbox */}
                    <div
                      onClick={() => {
                        setTermsAccepted(v => !v);
                        setTermsError(false);
                        if (authError.includes("COMPLIANCE")) setAuthError("");
                      }}
                      className={`w-5 h-5 shrink-0 mt-0.5 border flex items-center justify-center transition-all duration-200 cursor-pointer ${termsAccepted
                        ? "bg-emerald-500 border-emerald-400"
                        : termsError
                          ? "border-rose-500 bg-rose-500/10"
                          : "border-white/20 bg-transparent hover:border-emerald-500/50"
                        }`}
                    >
                      {termsAccepted && (
                        <svg width="10" height="10" viewBox="0 0 10 10" fill="none">
                          <path d="M1.5 5L4 7.5L8.5 2.5" stroke="black" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                      )}
                    </div>

                    <span className="text-[9px] font-mono text-slate-400 leading-relaxed uppercase tracking-wider">
                      I have read and agree to the{" "}
                      <button
                        type="button"
                        onClick={e => {
                          e.stopPropagation();
                          setShowTermsModal(true);
                        }}
                        className="text-emerald-400 hover:text-emerald-300 underline underline-offset-2 transition-colors font-bold"
                      >
                        Terms & Conditions
                      </button>
                      {" "}and acknowledge that ArshMind does not provide financial advice.
                      {termsError && !termsAccepted && (
                        <span className="block mt-1 text-rose-500 normal-case">
                          ↑ Required to proceed
                        </span>
                      )}
                    </span>
                  </label>
                </div>

                <button
                  type="submit"
                  disabled={isSigningIn}
                  className="w-full py-3.5 bg-emerald-500 hover:bg-emerald-600 disabled:bg-white/5 disabled:text-slate-600 text-black font-mono font-bold text-[10px] uppercase tracking-[0.2em] transition-all"
                >
                  {isSigningIn ? "[ INITIALIZING PROFILE... ]" : "[ COMPLETE REGISTRATION ]"}
                </button>

                <div className="flex justify-between items-center text-[9px] font-mono uppercase tracking-widest pt-2">
                  <button type="button" onClick={() => clearModes("CHOICE")} className="text-slate-500 hover:text-emerald-500 transition-colors">
                    &lt; RETURN_BACK
                  </button>
                </div>
              </form>
            )}

            {/* PASSWORD RESET */}
            {authMode === "RESET" && (
              <form onSubmit={handlePasswordReset} className="w-full space-y-4">
                <div className="text-[9px] font-mono text-slate-500 text-center uppercase tracking-widest mb-1">
                  // RECOVER_SECURITY_ACCESS_KEY
                </div>
                <div>
                  <label className="block text-[8px] font-mono text-slate-500 uppercase tracking-widest mb-1.5">
                    // TARGET_EMAIL_COORDINATE
                  </label>
                  <input
                    type="email"
                    value={email}
                    required
                    placeholder="ENTER_YOUR_REGISTERED_EMAIL"
                    onChange={e => setEmail(e.target.value)}
                    className="w-full bg-[#070708] border border-white/10 hover:border-white/20 focus:border-emerald-500/50 p-3 text-[10px] font-mono text-white placeholder:text-slate-600 focus:outline-none transition-all"
                  />
                </div>
                <button
                  type="submit"
                  disabled={isSigningIn}
                  className="w-full py-3.5 bg-emerald-500 hover:bg-emerald-600 text-black font-mono font-bold text-[10px] uppercase tracking-[0.2em] transition-all"
                >
                  {isSigningIn ? "[ TRANSMITTING RECOVERY ATOM... ]" : "[ INITIATE PASSWORD RECOVERY ]"}
                </button>
                <div className="flex justify-between items-center text-[9px] font-mono uppercase tracking-widest pt-2">
                  <button type="button" onClick={() => clearModes("SIGNIN")} className="text-slate-500 hover:text-emerald-500 transition-colors">
                    &lt; RETURN_TO_SIGNIN
                  </button>
                </div>
              </form>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}